version: '3.9'
services:
  web:
    build: .
    container_name: trono-remunerado
    ports:
      - "8080:80"
    environment:
      APP_NAME: "Trono Remunerado"
      APP_URL: "http://localhost:8080"
      APP_ENV: "local"
      APP_TIMEZONE: "America/Sao_Paulo"
      CONTACT_RECIPIENT_EMAIL: "contato@teonoremunerado.com"
    volumes:
      - ./storage:/var/www/html/storage
    restart: unless-stopped
